export const GET_ALBUMS_LIST = "GET_ALBUMS_LIST"
export const GET_ALBUMS_LIST_SUCCEEDED = "GET_ALBUMS_LIST_SUCCEEDED"
export const GET_ALBUMS_LIST_FAILED = "GET_ALBUMS_LIST_FAILED"
export const GET_ALBUMS_ID_READ = "GET_ALBUMS_ID_READ"
export const GET_ALBUMS_ID_READ_SUCCEEDED = "GET_ALBUMS_ID_READ_SUCCEEDED"
export const GET_ALBUMS_ID_READ_FAILED = "GET_ALBUMS_ID_READ_FAILED"
export const GET_ALBUMS_ID_TRACKS_LIST = "GET_ALBUMS_ID_TRACKS_LIST"
export const GET_ALBUMS_ID_TRACKS_LIST_SUCCEEDED =
  "GET_ALBUMS_ID_TRACKS_LIST_SUCCEEDED"
export const GET_ALBUMS_ID_TRACKS_LIST_FAILED =
  "GET_ALBUMS_ID_TRACKS_LIST_FAILED"
export const GET_ALBUMS_READ = "GET_ALBUMS_READ"
export const GET_ALBUMS_READ_SUCCEEDED = "GET_ALBUMS_READ_SUCCEEDED"
export const GET_ALBUMS_READ_FAILED = "GET_ALBUMS_READ_FAILED"
